PROJECT_NAME: "DummyData"
EXPERIMENT_NAME: "DummyDataModel"
TARGET_COL: "label"
ID_COLUMNS: ["risk_id"]
IGNORED_FEATURES: []
DATE_COL: "partition_date"
TRAIN_START_DATE: "2024-01-01"
TRAIN_END_DATE: "2024-08-31"
OOT_START_DATE: "2024-09-01"
OOT_END_DATE: "2024-09-30"